name: RodSpeed
version: 2.1
main: sypherox.RodSpeed
author: Sypherox

commands:
  rodspeed:
    description: Change the fishing rod speed with a multiplier
    usage: /rodspeed <multiplier>  |  /rodspeed reload
    permission: rodspeed.use

permissions:
  rodspeed.use:
    description: Allows use of the /rodspeed command
    default: op